# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: /opt/app
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache: # Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies- # fallback to using the latest cache if no exact match is found
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            pip install pylint
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "./venv"
      - run: # run lint!
          name: run lint
          command: |
            . venv/bin/activate
            make lint
